CREATE USER superset WITH PASSWORD 'superset';
CREATE DATABASE superset;
GRANT ALL PRIVILEGES ON DATABASE superset TO superset;

CREATE DATABASE userdata;
GRANT ALL PRIVILEGES ON DATABASE userdata TO airflow;
GRANT ALL PRIVILEGES ON DATABASE userdata TO superset;