CREATE USER superset WITH PASSWORD 'superset';
CREATE DATABASE superset;
GRANT ALL PRIVILEGES ON DATABASE superset TO superset;

CREATE DATABASE denver;
GRANT ALL PRIVILEGES ON DATABASE denver TO airflow;
GRANT ALL PRIVILEGES ON DATABASE denver TO superset;