CREATE TABLE IF NOT EXISTS public.traffic_accidents (
    objectid_1 int NULL,
    incident_id int NULL,
    offense_id int NULL,
    offense_code int NULL,
    offense_code_extension int NULL,
    top_traffic_accident_offense text NULL,
    first_occurrence_date text NULL,
    last_occurrence_date text NULL,
    reported_date text NULL,
    incident_address text NULL,
    geo_x int NULL,
    geo_y int NULL,
    geo_lon float8 NULL,
    geo_lat float8 NULL,
    district_id int NULL,
    precinct_id int NULL,
    neighborhood_id text NULL,
    bicycle_ind int NULL,
    pedestrian_ind int NULL,
    harmful_event_seq_1 text NULL,
    harmful_event_seq_2 text NULL,
    harmful_event_seq_3 text NULL,
    road_location text NULL,
    road_description text NULL,
    road_contour text NULL,
    road_condition text NULL,
    light_condition text NULL,
    tu1_vehicle_type text NULL,
    tu1_travel_direction text NULL,
    tu1_vehicle_movement text NULL,
    tu1_driver_action text NULL,
    tu1_driver_humancontribfactor text NULL,
    tu1_pedestrian_action text NULL,
    tu2_vehicle_type text NULL,
    tu2_travel_direction text NULL,
    tu2_vehicle_movement text NULL,
    tu2_driver_action text NULL,
    tu2_driver_humancontribfactor text NULL,
    tu2_pedestrian_action text NULL,
    seriously_injured int NULL,
    fatalities int NULL,
    fatality_mode_1 text NULL,
    fatality_mode_2 text NULL,
    seriously_injured_mode_1 text NULL,
    seriously_injured_mode_2 text NULL,
    load_date date NOT NULL
);


